#!/usr/bin/env bash

#i need to make it take any c file, not just something.c

if [ "${1##*.}" = c ]; then #if the file ends in .c, do this. This syntax is from the cheatsheet


touch file.c #create our temp. file


echo "/** 
* Filename: $(echo $1)
* Owner: $(ls -l $1 | awk '{print $3}')
* Last Modified On: $(ls -l $1 | awk '{print $7}') $(ls -l $1 | awk '{print $8}') $(ls -l $1 | awk '{print $9}')
*/" > file.c #take the file that was inputted and gain its information. Then, write it to file.c, our temporary file


cat $1>>file.c #expand the cat function, then stick the input into the end of file.c
cat file.c > "${1##*/}" #voodoo magic. write the contents of file.c to the FILE something.c . This is from the cheatsheet, $1 gives us the /path/to/something.c . This line of code just takes something.c! 

rm file.c

fi
